FROM registry.access.redhat.com/ubi9/python-311
WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --upgrade accelerate==1.6.0 \
                                         docling==2.28.4

USER 1001
